Add iTunes database
hack-different/apple-knowledge pull request #2
Opened 2021-12-07 22:13 UTC by jeanthom

2021-12-08 23:25 UTC, VelocityDesign requested changes
I'd recommend removing the listing on line #17, as it is archived by the owner.

2021-12-09 07:16 UTC, jeanthom commented
I'm the author of libitlp. Although the repository is archived, its implementation of itlp parsing is far more accurate than other itlp parsers.

2021-12-10 17:28 UTC, VelocityDesign commented
> I'm the author of libitlp. Although the repository is archived, its implementation of itlp parsing is far more accurate than other itlp parsers.

Ok sorry! I did not catch that you were the author.

2021-12-14 23:40 UTC, rickmark approved these changes

2021-12-14 23:40 UTC, merged